# -*- coding: utf-8 -*-
"""midi_scraper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwUED63S5JO6og_iJn43tr2jimhOIlOU
"""

!pip install requests
!pip install beautifulsoup4

import requests
from bs4 import BeautifulSoup, SoupStrainer

def scrape(link, depth, links):

    url = link
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    print_links(soup, depth, links)

def print_links(result, depth, links):
  for i in result.find_all('a', href=True):
    if i['href'].endswith('.htm') and not('classic.htm' in str(i['href'])) and depth:
      print(i['href'])
      scrape("https://www.midiworld.com/" + i['href'], False, links)
    if i['href'].endswith('.mid'):
      links.append(i['href'])

links = []
scrape('https://www.midiworld.com/classic.htm', True, links)

len(links)

